apps/loginreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^$', views.index, name="index"),
	url(r'^register$', views.register, name="register"),
	url(r'^login$', views.login, name="login"),
	url(r'^success$', views.success, name="success"),
	url(r'^logout$', views.logout, name = "logout")

]

apps/travel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^$', views.index, name="index"),
	url(r'^show$', views.show, name="show"),
	url(r'^show/(?P<id>\d+)$', views.show, name="show"),
	url(r'^join$', views.join, name="join"),
	url(r'^add$', views.add, name="add"),
	url(r'^add_travel$', views.add_travel, name="add_travel"),
	
	]

belt3/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.loginreg.urls', namespace = "login")),
    url(r'^travel/', include('apps.travel.urls', namespace = "travel")),
]

apps/loginreg/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt



# Create your models here.
class UserManager(models.Manager):
	def register_user(self, postData):
		errors = []

		if len(postData['name']) < 3:
			errors.append('Name must be at least 3 characters long.')

		if len(postData['username']) < 3:
			errors.append('Username must be at least 3 characters long.')

		if len(postData['password']) < 8:
			errors.append('Password name must be at least 8 characters long.')

		if not postData['password'] == postData['password_confirmation']:
			errors.append('Password fields must match.')

		if self.filter(username = postData['username']):
			errors.append('Please enter a username.')

		response_to_views = {}

		if not errors:
			hashed_password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
			user = self.create(name = postData['name'], username = postData['username'], password = hashed_password)
			response_to_views['user'] = user
			response_to_views['status'] = True

		else:
			response_to_views['errors'] = errors
			response_to_views['status'] = False

		return response_to_views


	def login_user(self, postData):
		user = self.filter(username = postData['username'])
		response_to_views = {}
		
		if not user:
			response_to_views['status'] = False
			response_to_views['errors'] = 'Username found.'

		else:
			if bcrypt.checkpw(postData['password'].encode(), user[0].password.encode()):
				response_to_views['status'] = True
				response_to_views['user'] = user[0]
				response_to_views['welcome'] = "Successfully logged in."

			else:
				response_to_views['status'] = False
				response_to_views['errors'] = 'Invalid username and/or password.'

		return response_to_views



class User(models.Model):
	name = models.CharField(max_length=255)
	username = models.CharField(max_length=255)
	password = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

	objects = UserManager()

apps/travel/models.py
from __future__ import unicode_literals
from datetime import date
from django.db import models
from ..loginreg.models import User

# Create your models here.
class UserManager(models.Manager):
	def add_new_destination(self, postData):
		errors = []

		if len(postData['name']) < 1:
			errors.append('Destination cannot be empty.')

		if len(postData['description']) < 1:
			errors.append('Description cannot be empty.')

		if date(postData['date_from']) < date.today():
			errors.append('Date cannot be in the past.')

		if date(postData['date_to']) < date.today():
			errors.append('Date cannot be in the past.')

		response_to_views = {}

		if not errors:
			destination = self.create(name=request.POST['name'], description=request.POST['description'], date_from=request.POST['date_from'], date_to=request.POST['date_to'])
			response_to_views['destination'] = destination
			response_to_views['status'] = True

		else:
			response_to_views['errors'] = errors
			response_to_views['status'] = False

		return response_to_views

class Destination(models.Model):
	name = models.CharField(max_length=255)
	description = models.TextField(max_length=1000)
	date_from = models.DateTimeField(null=True)
	date_to = models.DateTimeField(null=True)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ManyToManyField(User, related_name="destinations")

	objects = UserManager()

apps/loginreg/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
	return render (request, 'loginreg/index.html')

def register(request):
	response_from_models = User.objects.register_user(request.POST)
	print "-" * 50

	if response_from_models ['status']:
		request.session ['user_name'] = response_from_models['user'].name

		return redirect('travel:index')

	else:
		for error in response_from_models['errors']:
			messages.error(request, error)

		return redirect('login:index')

def login(request):
	response_from_models = User.objects.login_user(request.POST)
	print "-" * 50

	if response_from_models ['status']:
		request.session ['user_name'] = response_from_models['user'].name

		return redirect('travel:index')

	else:
		messages.error(request, response_from_models['errors'])
		return redirect('login:index')


def success(request):


	if not 'user_first_name' in request.session:
		messages.error(request, 'Must be logged in!')
		return redirect('login:index')

	return render(request, 'travel:index')
	

		

def logout(request):
	request.session.clear()
	return redirect('login:index')

apps/travel/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from datetime import datetime
from .models import Destination
from ..loginreg.models import User

# Create your views here.
def index(request):
	
	context = {
	"destinations": Destination.objects.all(),
		
	}

	return render(request, "travel/index.html", context)

def show(request, id):
	context = {
	"destinations": Destination.objects.all(),
		
	}
	return render(request, "travel/destination.html", context)

def join(request):
	pass

def add_travel(request):
	return render (request, "travel/add.html")

def add(request):
	
	response_from_models = Destination.objects.add_new_destination(request.POST)
	print "-" * 50

	if response_from_models ['status']:

		return redirect('travel:index')

	else:
		messages.error(request, response_from_models['errors'])
		return redirect('travel:add_travel')


	

apps/loginreg/templates/loginreg/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Login</title>
	
</head>
<body>

		
		{% if messages %}
			{% for message in messages %}
				<p>{{ message }}</p>
			{% endfor %}
		{% endif %}

		<p>Register</p>
		<form class = "" action="{% url 'login:register' %}" method="post">
			  {% csrf_token %}
			<label for="name">
				Name
				<input type="text" name="name" >
				</label>
			<label for="username">
				Username
				<input type="text" name="username">
			</label>
			<label for="password">
				Password
				<input type="password" name="password">
			</label>
			<label for="password_confirmation">
				Confirm Password
				<input type="password" name="password_confirmation">
			</label>
			<button type="submit" name="button">Register</button>
		</form>
	
	
	
		<p>Login</p>
		<form class = "" action="{% url 'login:login' %}" method="post">
			  {% csrf_token %}
			<label for="username">
				Username
				<input type="text" name="username">
			</label>
			<label for="password">
				Password
				<input type="password" name="password">
			</label>
			<button type="submit" name="button">Login</button>
		</form>


</body>
</html>

apps/travel/templates/travel/add.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Add Trip</title>
</head>
<body>
	
	{% if messages %}
		{% for message in messages %}
			<p>{{ message }}</p>
		{% endfor %}
	{% endif %}

	<h2>Add a Trip</h2>
		<form action="{% url 'travel:add' %}" method="POST">
			{% csrf_token %}
			<label for="name">
				Destination
				<input type="text" name="name" >
			</label>
			<label for="description">
				Description
				<input type="text" name="description">
			</label>
			<label for="date_from">
				Travel Date From
				<input type="date" name="date_from">

			</label>
			<label for="date_to">
				Travel Date From
				<input type="date" name="date_to">
			</label>
			<button type="submit" name="button">Add</button>
			</form>

	<form action="{% url 'travel:index' %}" method="post">
	  {% csrf_token %}
	    <input type="submit" name = "submit" value="Home" />
	</form>

	<form action="{% url 'login:logout' %}" method="post">
	  {% csrf_token %}
	    <input type="submit" name = "submit" value="Logout" />
	</form>




</body>
</html>

apps/travel/templates/travel/destination.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Destination</title>
</head>
<body>
	{% for destination in destinations %}
	
	<h2>{{destination.name}}</h2>
	
	<p>Description: {{destination.description}}</p>
	<p>Travel Date From: {{destination.date_from}}</p>
	<p>Travel Date To: {{destination.date_to}}</p>

	{% endfor %}

	<form action="{% url 'travel:index' %}" method="post">
	  {% csrf_token %}
	    <input type="submit" name = "submit" value="Home" />
	</form>

	<form action="{% url 'login:logout' %}" method="post">
	  {% csrf_token %}
	    <input type="submit" name = "submit" value="Logout" />
	</form>

</body>
</html>

apps/travel/templates/travel/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Success</title>
</head>
<body>
<h1>Success! Welcome, {{request.session.user_name}} </h1>

	{% if messages %}
			{% for message in messages %}
				<p>{{ message }}</p>
			{% endfor %}
		{% endif %}

	<p>Your Trip Schedules</p>
	<table>
		<tr>
			<th>Destination</th>
			<th>Travel Start Date</th>
			<th>Travel End Date</th>
			<th>Plan</th>
		</tr>
		{% for destination in destinations %}
		<tr>
			<td><form action="{% url 'travel:show' id=destination.id %}">{% csrf_token %}<input type="submit" value="{{destination.name}}"></form></td>
			<td>{{destination.date_from}}</td>
			<td>{{destination.date_to}}</td>
			<td>{{destination.description}}</td>
        </tr>
		{% endfor %}
            
    </table>

    <br>

   <form action="{% url 'travel:add_travel' %}" method="post">
	  {% csrf_token %}
	    <input type="submit" name = "submit" value="Add Travel Plan" />
	</form>
	
	<br>

	<form action="{% url 'login:logout' %}" method="post">
	  {% csrf_token %}
	    <input type="submit" name = "submit" value="Logout" />
	</form>

</body>
</html>